exports.EVENT_ADD_TEMPLATE = 'EVENT_ADD_TEMPLATE';
exports.EVENT_DELETE_TEMPLATE = 'EVENT_DELETE_TEMPLATE';
exports.EVENT_LIST_TEMPLATE = 'EVENT_LIST_TEMPLATE';
exports.EVENT_DETAIL_TEMPLATE = 'EVENT_DETAIL_TEMPLATE';
exports.EVENT_RC_CONFIG_NOT_FOUND = 'EVENT_RC_CONFIG_NOT_FOUND';
